// Privacy notice — content requires DPO sign-off before go-live.
// The data categories and retention periods below are technically accurate;
// the legal framing must be reviewed by the college Data Protection Officer.

export default function PrivacyPage() {
  return (
    <div className="max-w-2xl space-y-8">
      <div>
        <p className="text-xs font-medium text-amber-700 bg-amber-50 border border-amber-200 rounded px-3 py-2 mb-4">
          Draft — pending Data Protection Officer sign-off
        </p>
        <h1 className="text-2xl font-semibold tracking-tight">Privacy notice</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Room Booking Platform · Greenhead College · Last updated: June 2026
        </p>
      </div>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">What we collect</h2>
        <table className="w-full text-sm border-collapse">
          <thead>
            <tr className="border-b text-xs text-muted-foreground">
              <th className="pb-2 text-left font-medium w-1/3">Category</th>
              <th className="pb-2 text-left font-medium w-1/3">Source</th>
              <th className="pb-2 text-left font-medium">Retention</th>
            </tr>
          </thead>
          <tbody className="divide-y">
            <tr>
              <td className="py-2 pr-4">Name, UPN, group membership</td>
              <td className="py-2 pr-4">Microsoft Entra ID (on sign-in)</td>
              <td className="py-2">Until account removed from Entra</td>
            </tr>
            <tr>
              <td className="py-2 pr-4">Room booking records</td>
              <td className="py-2 pr-4">Exchange calendar (mirrored)</td>
              <td className="py-2">As long as present in Exchange</td>
            </tr>
            <tr>
              <td className="py-2 pr-4">Audit log entries</td>
              <td className="py-2 pr-4">Generated by the platform</td>
              <td className="py-2">2 years, then archived and deleted</td>
            </tr>
            <tr>
              <td className="py-2 pr-4">Session tokens</td>
              <td className="py-2 pr-4">Generated on sign-in</td>
              <td className="py-2">30 days or sign-out (whichever first)</td>
            </tr>
            <tr>
              <td className="py-2 pr-4">Device pairing records</td>
              <td className="py-2 pr-4">Enrolled by IT administrators</td>
              <td className="py-2">Until device is revoked by an admin</td>
            </tr>
          </tbody>
        </table>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">Where data is stored</h2>
        <p className="text-sm">
          Data is stored in a PostgreSQL database and Redis cache hosted on{" "}
          <strong>Railway</strong> (EU West region). Booking metadata is also
          held in <strong>Exchange Online</strong> room mailboxes (Microsoft
          365, EU data residency). No data is transferred outside the European
          Economic Area.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">Cookies</h2>
        <p className="text-sm">
          This site sets a single <strong>session cookie</strong> (
          <code className="text-xs bg-muted px-1 rounded">session</code>) to
          keep you signed in. It is HTTP-only, secure, and expires after 30
          days of inactivity. No tracking, analytics, or third-party cookies
          are used.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">Your rights</h2>
        <p className="text-sm">
          Under UK GDPR you have the right to access, correct, or request
          deletion of your personal data. To make a Subject Access Request or
          request deletion, contact{" "}
          <a
            href="mailto:it@greenhead.ac.uk"
            className="underline hover:text-foreground"
          >
            it@greenhead.ac.uk
          </a>
          .
        </p>
        <p className="text-sm">
          The Data Controller is Greenhead College. The Data Protection Officer
          can be contacted at{" "}
          <a
            href="mailto:dpo@greenhead.ac.uk"
            className="underline hover:text-foreground"
          >
            dpo@greenhead.ac.uk
          </a>
          .
        </p>
      </section>
    </div>
  );
}
