rooms:
  # -------- Cooksey --------
  - id: "ct12"
    mailboxUpn: "ct12@greenhead.ac.uk"
    displayName: "CT12"
    building: "Cooksey"
    capacity: 12
    equipment: []
    allowedGroups:
      - "be1c4aa6-38e4-4232-bd61-955e63121fb1" # All Staff

  # -------- Dawson --------
  - id: "d3a"
    mailboxUpn: "d3a@greenhead.ac.uk"
    displayName: "D3A"
    building: "Dawson"
    capacity: 12
    equipment: []
    allowedGroups:
      - "be1c4aa6-38e4-4232-bd61-955e63121fb1" # All Staff

  - id: "d17"
    mailboxUpn: "d17@greenhead.ac.uk"
    displayName: "D17"
    building: "Dawson"
    capacity: 12
    equipment: []
    allowedGroups:
      - "be1c4aa6-38e4-4232-bd61-955e63121fb1" # All Staff
